# Generated by Django 3.0.3 on 2020-03-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_blog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='picture',
            field=models.CharField(default='', max_length=300),
        ),
    ]
