# Generated by Django 3.0.3 on 2020-03-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_tool_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='picture',
        ),
        migrations.AddField(
            model_name='tool',
            name='photo',
            field=models.ImageField(default=None, upload_to='site_media'),
            preserve_default=False,
        ),
    ]
