# Generated by Django 3.0.3 on 2020-03-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_auto_20200328_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='photo',
            field=models.ImageField(default='bootstraplogo', upload_to='img'),
        ),
    ]
