# Generated by Django 3.0.3 on 2020-03-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_auto_20200328_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='site_media'),
        ),
    ]
