# Generated by Django 3.0.3 on 2020-04-10 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0010_auto_20200328_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['due']},
        ),
        migrations.AddField(
            model_name='tool',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tool',
            name='due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('r', 'Reserved'), ('c', 'Checked out'), ('a', 'Available')], default='a', max_length=1),
        ),
    ]
